# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-22 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TVapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channels',
            new_name='Channel',
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='Shows',
            new_name='Show',
        ),
    ]
